version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  microblog:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: "mysql+pymysql://microblog:${MYSQL_PASSWORD}@db:3306/microblog"
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
